# Copyright 2021 SLAC for the benefit of the SuperCDMS collaboration.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Authors:
# - Kenny Lo <kennywlo@slac.stanford.edu>, 2021

# To build this image to use with docker-compose:
#   docker build -f ./Dockerfile_DC -t tomcat:datacat-v0.6-dep .

FROM tomcat:8.5-jdk8-openjdk

MAINTAINER kennylo@slac.stanford.edu

ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends apt-utils
RUN apt-get -y install libaio1
 
ENV ORACLE_HOME=/sdf/sw/Oracle/product/18.9.0/dbhome_1
ENV CLASSPATH=/sdf/sw/Oracle/product/18.9.0/dbhome_1/jdbc/lib/ojdbc8.jar
ENV LD_LIBRARY_PATH=/usr/local/tomcat/native-jni-lib:/sdf/sw/Oracle/product/18.9.0/dbhome_1/lib

